### ISSUE TITLE
one-to-many: the "one" object gets created even if the "many" object doesn't validate

### ISSUE THREAD

**Issue by aaronz8** [balderdashy/waterline#1051]
// "many" object
    var credential = {
      email: 'not@unique.com', // unique: true 
      password: 'password',
      _user: {profile: {lol: 'lolll'}} // "one" object. In this case I want to create a new user instead of associating with an existing user
    };

    try {
      yield this.models.credential.create(credential);
    } catch (err){
      console.log(err); // AdapterError: Record does not satisfy unique constraints
    }

In this example, a `user` may have many `credential`s. `credential`s have a unique email field. When `create`ing an invalid `credential`, it'll fail to save the new `credential` on the db (as expected), but will save an orphan `user`(unexpected). 

Is this by design? Is there an option to turn this behavior off?

**Comment by dmarcelino** [comment]
Hi @aaronz8, the nested records are created before the parent record (so later they can be associated with the parent record). I don't think it will be possible to change this behaviour (or at least it will be very difficult) until transactions (#755) are in place.

Your best option for now is to create `credential` first and, if successful, update it with `_user `. If I'm counting correctly this will take 3 trips to the DB instead of 2, so it shouldn't be too bad.

**Comment by aaronz8** [comment]
Yup, seems like it'll just be a few more db calls and some additional error handling, but nothing too drastic.
Thanks for the quick response and explanation!
