### ISSUE TITLE
creation failure will cause the auto increment index to be changed.

### ISSUE THREAD

**Issue by calidion** [balderdashy/waterline#1086]
User.create({
        username: 'aaa',
        password: '',
        confirm: ''
      })

if I execute username twice, the creation will fail but the autoincrement index will be changed.

for current autoincrement index equals 1,
after execution success, the index wil be 2.
than a failure execution will change the index to be 3. 
thought there is no new user generated.
and the following new use index will start from 4.

**Comment by dmarcelino** [comment]
Hi @calidion, that sounds like an adapter issue since the index is handled by the adapter (or datastore). Which adapter are you using? Have you tried a different adapter? It's probably worth moving this issue to the [specific adapter project](https://github.com/balderdashy/waterline-docs#supported-adapters).

**Comment by calidion** [comment]
@dmarcelino 
should be mysql-adapter.

**Comment by devinivy** [comment]
You may open an issue in sails-mysql if you wish, but what you're referring to is an intentional property of InnoDB tables, which is trying to account for transactional queries.

You may be able to configure this behavior manually: http://dev.mysql.com/doc/refman/5.1/en/innodb-auto-increment-handling.html#innodb-auto-inc.  Also see http://stackoverflow.com/questions/2787910/why-does-mysql-autoincrement-increase-on-failed-inserts.

**Comment by particlebanana** [comment]
Yup, gotta love databases!
