### ISSUE TITLE
Get current values inside beforeUpdate hook

### ISSUE THREAD

**Issue by talyssonoc** [balderdashy/waterline#1094]
I need to be able to compare the previous value with the new one and assign a new attribute under some condition in a `beforeUpdate` callback. For example:

```js
    beforeUpdate: function(newValues, callback) {
       if(/* currentValues */.age > newValues.age) {
         newValues.permission = false;
       }
    }
```

How could I access the `currentValues` ?

**Comment by particlebanana** [comment]
You will need to do a lookup and get them. The problem is that you may or may not have a unique identifier based on what is sent to the update.

**Comment by talyssonoc** [comment]
Well, in my case I'll always have a unique key for this. Thanks !

**Comment by animedbz16** [comment]
This seems like an attempt at optimistic locking. Only allow updating an object if a specific unique attribute is also passed along. 

I this case it looks like you are using the object's time stamp and ensuring that the new object is newer than the old one, otherwise you want to deny it to be updated.

I would think that waterline itself should provide a feature for optimistic locking
https://github.com/balderdashy/waterline/issues/426
