### ISSUE TITLE
many to many fires involuntary update in model

### ISSUE THREAD

**Issue by dakairus** [balderdashy/waterline#1105]
Hi guys, just checking the issues and I don't found anything similar to my situation. I have a many to many relation between 2 models. when I create a model, inside the fields list, I provide a array of ids of the other entity to make the relation between the models. I figured out that after the model creation it fires a update event on the model when it creates the relations. Usually this is not a problem, the real problem came because some of the fields of the first model have sensitive data, so I got to encrypt them in the database. I made the encryption in the beforeCreate and beforeUpdate event. Because this involuntary update the sensitive fields on the first model are encrypted 2 times, so to generate the relation without double encrypt I have to generate the relation from the second model and works everything fine.

Exist a option to turn of this update or some kind of approach to fix this?

Thanks in advance.

**Comment by devinivy** [comment]
This is true!  There's a sometimes-unnecessary `save` that occurs with nested operations (operations on one-to-many or many-to-many relationships).  I think we'd like to see a PR fixing the problem.  There's another case that it can happen too– when saving one-to-many relationships explicitly inside `update`.  Waterline will re-set foreign keys using an additional `update`.

I believe @RWOverdijk has made great progress on this here: #1048, meaning there's a good shot it'll be fixed in 0.11.

If you're curious, I bet this is your offender: https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/nestedOperations/create.js#L61
Those nested updates are run here in `create`: https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/dql/create.js#L230

**Comment by dmarcelino** [comment]
Yeap, like @devinivy said this should be fixed by PR #1048. You can also look at #683 which describes more or less what you are experiencing.

**Comment by dakairus** [comment]
Thx for the info guys, hope that 0.11 release comes soon. By the moment I'm solving the issue to not make the relations from the same entity, I'm in a project that is just starting so hope that the release is ready when the project is finishing.

Keep going with this great work!
