### ISSUE TITLE
No documentation for join() for Custom Adapters

### ISSUE THREAD

**Issue by gaurav21r** [balderdashy/waterline#1131]
I was wondering how adapters can override `populate()` in my adapter while going through balderdashy/waterline#1052

There seems to be No documentation on how to do this either here-> https://github.com/balderdashy/sails-docs/blob/0.9/adapter-specification.md
Which seems to be the major place for documentation of adapters.

I found it manually while looking over `sails-mongo` and `sails-mysql`. The fact that the method's name is `join()` while accessing it outside the adapter is `populate()` is counter intuitive. At least there should be docs for this.

@particlebanana @dmarcelino @devinivy What do you say?

**Comment by particlebanana** [comment]
Yup! It's a pretty big performance piece and should definitely have some documentation around it.

Basically if you have a `.join` method on your adapter Waterline will pass the whole normalized query object to that method instead of doing multiple find's. Any adapter with a `.join` method should know how to do actual SQL joins or at least how to handle waterline's join objects.

**Comment by particlebanana** [comment]
@gaurav21r let's move this to [waterline-docs](https://github.com/balderdashy/waterline-docs). Mind opening an issue over there?

**Comment by gaurav21r** [comment]
Sure!
