### ISSUE TITLE
Set 'string' as default for Primary Key Type

### ISSUE THREAD

**Issue by smith64fx** [balderdashy/waterline#1140]
Hello friends,
I have a quick question to you.

I am currently developing an adapter for SPARQL. Every Ressource there is unique and can have multiple models. So I must generate an UUID for each model.

So, the default for IDs are Integer. Is there any way to change this to string in general for this adapter?

**Comment by devinivy** [comment]
Yes– the adapter should have a property called `pkFormat` which waterline-schema takes into account when building the schema.  We have a [similar case](https://github.com/gadelkareem/sails-dynamodb/blob/master/index.js#L98) in sails-dynamodb.

**Comment by smith64fx** [comment]
Hi @devinivy thank you for your quick answer.

I also used this pkFormat but as I read in another post, this is not in use.
https://github.com/balderdashy/sails-mongo/issues/160

I see in mongodb, they set the PK Format manually when they define the collection. I think that's the way we have to do it.

**Comment by devinivy** [comment]
If it's not working, please file an issue with waterline-schema.  mongodb is a special case because its primary key needs such special treatment, and I wonder if that may be a confounding factor.  Here's where waterline-schema is supposed to take it into account: https://github.com/balderdashy/waterline-schema/blob/master/lib/waterline-schema/attributes.js#L207

**Comment by particlebanana** [comment]
Yes it should be taken into account now. If you have further issues please make an issue on the waterline-schema repo.
