### ISSUE TITLE
findOrCreate creates duplicates

### ISSUE THREAD

**Issue by kolbma** [balderdashy/waterline#1185]
Hi,
if I do something like

for (var i=0; i<30; i++) {
waterline.collections.mymodel.findOrCreate({ip: ip, code: code}, {ip: ip, code: code}, function(err, row){});
}

in a mocha test, I get multiple rows with {ip: ip, code: code} in my sails-disk-db.

**Comment by devinivy** [comment]
That's because you're trying to create many records at once, not waiting for previous queries to complete.  I suggest looking into using the [`Items.serial()`](https://github.com/hapijs/items) or [`Async.series()`](https://github.com/caolan/async) utilities to make asynchronous requests in a particular order.

**Comment by kolbma** [comment]
Mmh. Makes this method any sense in a database orm framework if it does not guarantee anything?
I would say this method is not thread safe. And such a method makes only sense if it is thread safe.

**Comment by devinivy** [comment]
There is a plan for transaction support in #1141, which is as far as I think we get get you.  Bear in mind that I/O (such as database queries) will inherently be done asynchronously in javascript.  It's just a characteristic of the language.  I'm going to close this because I don't think we can get much further with current features and plans, but I'd encourage suggestions for a well-spec'd feature request.  We can talk about that here a bit despite the original issue being closed.

**Comment by nrempel** [comment]
I think this issue is more related to https://github.com/balderdashy/waterline/issues/1259. This problem cannot be solved with a transaction and needs a distributed locking mechanism.
