### ISSUE TITLE
promise, doc explanation

### ISSUE THREAD

**Issue by gadidev** [balderdashy/waterline#1264]
I am looking at the example in https://github.com/balderdashy/waterline that shows a `promise`

```javascript
User.findOne()
.where({ id: 2 })
.then(function(user){
    var comments = Comment.find({userId: user.id}).then(function(comments1){
        return comments1;
    });
    return [user.id, user.friendsList, comments];
}).spread(function(userId, friendsList, comments){
    // Promises are awesome!
})
```

It seems to me that,  `comments` will be a promise, and the return value `comments1` is lost.   The function in `.spread()` can never access the comments which was the _intention_ of the code.

Am I wrong?

**Comment by devinivy** [comment]
Actually, whatever a `then()` callback returns will be promisified.  This is how promise chaining works.  However, in this case you're right that it looks funny because it's not necessary.  Here are two examples... you can see from the output that they do the same thing: https://tonicdev.com/devinivy/567bff50b573610c005a2d7d

**Comment by gadidev** [comment]
Thanks, I get it now.  The result, comments1, would have been promisified, and would become the fulfillment passed to the .spread() call.
