### ISSUE TITLE
Automatic attributes "mapping" for legacy database/nosql

### ISSUE THREAD

**Issue by adcoolguy** [balderdashy/waterline#1315]
We have tons of existing tables and columns. We would like to avoid defining the attributes in each Sails models. Maybe something like along adapter.decribe()? Not even sure adapter.decribe() exists and how to use it. It would be good even if it is an offline tool. But the best is, it should work like Rails ActiveRecord. No mapping needed!

Any answer would be highly appreciated ASAP. Thanks so much!

**Comment by irlnathan** [comment]
Howdy @adcoolguy,

This sounds like something that would be a great addition. I just want to be consistent about running this sort of change through the proposal process since it changes usage. It's the only way to make sure new features/enhancements are documented and tested, and for us to keep our sanity ^_^. Check out  the new [contribution guide](urlhttps://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) and submit as a proposal.

Best, Irl

**Comment by adcoolguy** [comment]
Can we have the link to the proposal? It is something like StrongLoop's https://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases.
