### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by aubinlorieux** [balderdashy/waterline#295]
It would be nice to have a validation for `unique: true` not only by the database.

I have try a custom validation but seems to not work in async

```javascript
types: {
   isUnique: function(value) {
      Team.find().where({number: value}).exec(function(err, team){
         if(err) return false;
         if(team.length > 0) return false;
         return true;
      });
   }
},

attributes : {
   number: {
      type: 'integer',
      required: true,
      unique: true,
      min: 1,
      isUnique: true
   }
}
```

Also when you change **unique** to `unique: false` with *MongoDB* the index isn't drop. You have to do it manually like this in the mongo console : 

```
db.team.dropIndex({number: 1})
````

**Comment by dmarcelino** [comment]
@mphasize, @gaprl regarding *async validations* please open a new issue detailing the feature and how you think it should work, with some examples.

@diosney, regarding error messages please add your comment to #148 which is were it's being handled.

I believe @particlebanana's answer (https://github.com/balderdashy/waterline/issues/295#issuecomment-36771416) properly answers this issue so I'm closing it, please reopen if you feel otherwise.
