### ISSUE TITLE
SQL Commands Monitoring

### ISSUE THREAD

**Issue by thomasdashney** [balderdashy/waterline#555]
Apologies if this exists somewhere and I couldn't find it--
is there a way to monitor all of the raw sql commands that waterline (I guess specifically, the adapter) is making to my database? This would make troubleshooting/optimization of database calls through the ORM much easier..

For instance, seeing the join syntax or how waterline maps models to schemas.

Thanks!

**Comment by devinivy** [comment]
The mysql adapter can do this when environment variable `LOG_QUERIES` is `true`.

The sails-postgresql adapter does not have this functionality, but if you'd like to help get it in, add a PR or issue over at https://github.com/balderdashy/sails-postgresql.

**Comment by slavafomin** [comment]
Why is this closed? Looks like a legitimate feature to me.

**Comment by wulfsolter** [comment]
@slavafomin Because "log queries" functionality is covered by all adapters as a built in function, and is pretty easy to set up. Adding this to sails would break the separation of concerns principles.

https://stackoverflow.com/questions/22401062/how-to-show-queries-in-console-log-using-sails

Feature requests are not issues, hence why it got moved to milestones and this issue closed.

**Comment by slavafomin** [comment]
Isn't the purpose of database abstraction layer to abstract the differences between all the databases and provide a single interface?

The [Doctrine supports it](http://vvv.tobiassjosten.net/symfony/logging-doctrine-queries-in-symfony2/).

Sequelize also [has such functionality](http://docs.sequelizejs.com/en/latest/api/sequelize/).

Hibernate [do too supports this](http://docs.jboss.org/hibernate/core/3.5/reference/en/html/session-configuration.html#configuration-logging).

**Comment by ALenfant** [comment]
I agree, it's very disappointing that waterline doesn't abstract this. It seems almost obvious to me, coming from the Python/Django world.

**Comment by wulfsolter** [comment]
Waterline supports this, check out 1.x branch.

**Comment by azarus** [comment]
> Waterline supports this, check out 1.x branch.

You know that many are coming from google looking for an actualy HOW TO. just like i do. Would be so bad to provide a link to the docs instead of saying xxx verison has it?

**Comment by tugorez** [comment]
Hi guys... it's been a long time
We, at spaceshiplabs, are using the sails-postgres wich uses pg as the postgres adapter.
Unfortunately the [pg module](https://github.com/brianc/node-postgres) doesnt support logging the queries see [this](https://github.com/brianc/node-postgres/issues/433). It is "suggested" [by the author](https://gist.github.com/brianc/1663864) to monkey patch the submit function (in the Query module) in order to do that. We are not sure about monkey patching being the right solution but sure a good workaround in the short term.
We are making something like this
```javascript
const Query = require('pg').Query;
const submit = Query.prototype.submit;
Query.prototype.submit = function() {
  const text = this.text;
  const values = this.values;
  const query = values.reduce((q, v, i) => q.replace(`$${i + 1}`, v), text);
  console.log(query);
  submit.apply(this, arguments);
};
```
And we are doing 2 separate modules in

1. The [pg-debug](https://github.com/spaceship-labs/pg-debug) module
2. The [sails-postgres-debug](https://github.com/spaceship-labs/sails-postgres-debug) hook to mount it only when NODE_ENV=development

Both projects started today so we will be fastly experimenting. I hope you find this is useful

**Comment by tugorez** [comment]
I'm also seeing if some of this stuff can be avoided by providing the right utilities in the node-postgres module.
