### ISSUE TITLE
afterCreate no longer contains id of created item

### ISSUE THREAD

**Issue by dustinbolton** [balderdashy/waterline#661]
I had working code that made use of the numeric primary key ID number of the newly created record. Updated updating from 0.9.x to 0.10.x I find the id is no longer present in the newlyInsertedRecord parameter passed to afterCreate.

Is this intentional?

**Comment by whitlockjc** [comment]
I was just bitten by this as well.  Basically, I have data in an existing MySQL database.  I've set `autoPk` to `false` because I do not want Waterline managing my ids.  When I use `MyModel#create` the returned object does not have the `id` set but when I do a `MyModel#find`, the returned models have the `id` field provided.

If I'm using Waterline with an existing database, why should I have to set `autoIncrement` to `true`?  Since this seems to be the fix for some, what can I expect this to change other than fixing this issue?

**Comment by devinivy** [comment]
This is genuinely up to the adapters to implement, so I suggest moving this over to sails-mysql.  Some databases will return the created records upon create, and others wont.  So the adapters can make their own decisions about where an extra lookup is necessary.

In the case of sails-mysql I can tell you that it avoids having to perform another lookup.  It does this by asking for the inserted id, which it can only do when using an auto-increment property (see [this](https://github.com/felixge/node-mysql/#getting-the-id-of-an-inserted-row)).  If you're managing your own ids, then it seems that the id should be present in the created record, since you set it yourself.

I'm going to let this issue remain open a little while longer if there are clarifying questions, etc., but please raise any additional concerns on the appropriate adapter's repo.  Hope this helped!

**Comment by dmarcelino** [comment]
As @devinivy stated this is an adapter issue, please raise it in the appropriate adapter's project. Feel free to re-open if you think this hasn't been fully answered.
