### ISSUE TITLE
Support 'long' integer

### ISSUE THREAD

**Issue by lghamie** [balderdashy/waterline#786]
I think that a 'long' data type could be useful. Currently 'integer' is the only option, and it doesn't accept values longer than (2³² -1).

I've been trying, but i can't find a hack to save a value larger than (2³² -1).

Thanks for the awesome work!

**Comment by particlebanana** [comment]
It looks like postgres at least has a `bigint` field https://github.com/balderdashy/sails-postgresql/blob/master/lib/utils.js#L240-L241 not sure if it works seamlessly though. Which adapter are you using?

**Comment by lghamie** [comment]
Sorry for the delay! Mysql

**Comment by devinivy** [comment]
@lghamie there's pending PR ing the mysql adapter for this exact functionality: https://github.com/balderdashy/sails-mysql/pull/209
I suggest subscribing to that PR so that you know when this functionality goes through.  The way that will work is by using a `size` property on your attribute to specify `8`, `16`, `32`, or `64` as the number of bits for the integer.

In the meantime, if your migration strategy is set to `safe` you can migrate column definitions without waterline interfering.  In mysql you can have up to 64bit integers using the column type `BIGINT`.  See http://stackoverflow.com/questions/14573451/mysql-size-limits-to-integer-columns.

Does that sufficiently answer your questions?

**Comment by sixpounder** [comment]
Btw, after I opened the PR I started working on the implementation for Postrgres. If the PR for mysql gets merged, I will open the other one as well

**Comment by lghamie** [comment]
Yep, closing.
