### ISSUE TITLE
beforeCreate filling required fields

### ISSUE THREAD

**Issue by KeKs0r** [balderdashy/waterline#800]
Hi,

I faced this issue already multiple times, that I want some "required" field to be filled in beforeCreate(), but then the Validation fails. Is there a way to make a Field not required for validation, but pass the "required" to the actual database schmema (e.g. mysql)?

**Comment by randallmeeker** [comment]
?? If it's required in your MySQL schema then your database will return an error even if you skip the validation on the waterline side. Or am I missing something?

**Comment by tjwebb** [comment]
A field cannot be both required and not required.  -__-

**Comment by randallmeeker** [comment]
@tjwebb Technically it can. In other frameworks I have required onCreate, but not onUpdate and other use cases where sometimes required and sometimes not required. Now it can't be both in the actual DB schema, and it can't be required in the DB schema and not in the Waterline model. But I think his is a mis-communication on his part perhaps.

**Comment by KeKs0r** [comment]
I need it to be required by the schema but NOT required by the waterline validation, because it is filled in beforeCreate. So the database should require it, but since waterline validation requires it as well, it never goes into beforeCreate because it already fails on validation.

**Comment by tjwebb** [comment]
It can be filled in beforeValidate, then, and not beforeCreate.

**Comment by KeKs0r** [comment]
Yes I guess I have to fill it in beforeValidate, I just thought beforeCreate would be the more appropriate Hook. But if that is foreseen like that. Thats what I gonna do.

**Comment by n8maninger** [comment]
@KeKs0r I just ran into this in a personal project I was working on. The problem I saw with using beforeValidate to set values for creation is that beforeValidate shares a callback with the update lifecycle. 

I was running into issues with my records regenerating things on update. I ended up having to take the generation out of the model entirely, which isn't necessarily bad.

**Comment by tjwebb** [comment]
yea to @n8maninger's point, if you find yourself doing this sort of data population to the point it becomes onerous or uncomfortable, then it's time to rethink some other things about your design.

**Comment by randallmeeker** [comment]
You can separate update/create in the beforeValidate by looking for the PK of the model.

**Comment by particlebanana** [comment]
Wouldn't that be a default value?

**Comment by ansel1** [comment]
@randallmeeker the PK of the model is not passed to beforeValidate on updates.  Only the updated values are passed.

I'm running into this too, implementing a simple "token" field.  It's required, and it's auto-generated on create.  Shouldn't ever be updated.  Seems like I need to enforce these rules myself in beforeCreate and beforeUpdate callbacks, instead of leaning on the validation framework.  This is pretty awkward though, since I have to carefully build my own WLValidationErrors to throw.

I have another data constraint that's hard to implement: 'name' should be unique within a certain query scope.  I implemented this in an afterValidation() callback: if 'name' is in 'values', run the db query looking for duplicates.  But on updates, I don't know the PK of the record being updated.  So I can't exclude it from the duplicate query.  Even beforeUpdate() suffers this limitation: it doesn't know the PK of the model being updated.  

Seems like the model should be responsible for data integrity.  I could create static methods on my model to intercept all create/update operations and enforce integrity there.  Can I override the create() and update() built-ins maybe?

**Comment by dmarcelino** [comment]
@ansel1, have you found an answer to your issue? Can you share it?

Any pending queries related to this topic?

**Comment by n8maninger** [comment]
@dmarcelino at some point a while back Waterline implemented functions for defaultsTo.

``` javascript
id: {
            type: 'text',
            primaryKey: true,
            unique: true,
            defaultsTo: function() { return uuid.v4(); }
        }
```

**Comment by dmarcelino** [comment]
Ah, nice, thanks, we should add that to https://github.com/balderdashy/waterline-docs/blob/master/models.md#defaultsto! :wink:
