### ISSUE TITLE
provide example of using update with promises.

### ISSUE THREAD

**Issue by airtonix** [balderdashy/waterline#801]
Perhaps I'm not as smart as I'd like to be, so I'm not immediately groking how an update query using promises would look.

This is how I think it might work (since the callback based approach requires two dictionaries arguments before the callback : 

```coffee
...

Model
    .update user: token.user
    .with valid: false
    .then (model)->
        # get our boats and hoes and have a great time.

...
```

Or does the `.update` method still take a `query` and the `fields:values` dictionaries?

**Comment by tjwebb** [comment]
Model.update(...).then(...)

But also I can't read coffeescript (or whatever that is) so it's hard for me to know if that's right or wrong

**Comment by airtonix** [comment]
Coffeescript is actually really simple: indentation matters, don't need to use braces, don't use semi-colons, functions are written as `(parameter1, parameter2)->`


Anyway, you didn't really answer the question: 
When using promises, where does the update dictionary/object/hash/associative-array/thingthathasstuff go? in the update method? in another method afterwards (because `find` and `findBlahLol`  can use `.where`) ... ?

**Comment by tjwebb** [comment]
Well it's not as simple as Javascript, in that every web developer on the planet already knows Javascript. But anyway:

I don't really know what your question actually is. Your update parameters go in the update() call, per usual. Nothing about the waterline API changes, except you call `.then()` instead of `done()` or passing a callback. For general info about promises, read through the Bluebird docs (https://github.com/petkaantonov/bluebird/blob/master/API.md). (btw, with `find()` you can just put the where clause inside the find() arguments. you don't need a separate .where call. more on this in the sails.js docs)

**Comment by airtonix** [comment]
Haha wow. you got up on the wrong side of the bed today... lol.

`Well it's not as simple as Javascript`

No. really it is actually. :)

`... I don't really know what your question actually is. ...` 

Your reply says otherwise. :)

Hope you find something to make your day better because taking it out on other people won't do that.

:)

**Comment by tjwebb** [comment]
Ok you're done trolling here. I spent time trying to help you, but the real solution is for you to RTFM.

**Comment by particlebanana** [comment]
```javascript
Model.update({ name: 'fido', age: 25 })
.then(function(model) {
   // handle code here
});
```
