### ISSUE TITLE
Nested populate timeline?

### ISSUE THREAD

**Issue by devjones** [balderdashy/waterline#849]
First off, huge thanks to all contributors for this project.  I think it has potential to be the best ORM for node.js.

I see some work is currently being done to allow nested populate/joins.  Any rough time estimates on when this would be ready?

**Comment by aaronshaf** [comment]
+1

**Comment by albertkim** [comment]
People have been requesting this for over a year now.

**Comment by aaronshaf** [comment]
I just moved back to Sequelize.

**Comment by dmarcelino** [comment]
Hi, AFAIK there is no timeline for this yet. From what I can gather this is a rather difficult change due to waterline associations supporting associations across different adapters/databases. That challenge is what has been holding this. For more on this please refer to #308 and continue the discussion there.

Closing this as a duplicate.
