### ISSUE TITLE
(bug) 1-N association serious data inconsistency

### ISSUE THREAD

**Issue by anasyb** [balderdashy/waterline#907]
With mongo, assume we have a user:
```javascript
posts: {
    collection: 'post',
    via: 'owner'
}
```
and obviously post:
```javascript
owner: {
    model: 'user'
}
```
Now let's create a user first:
```javascript
User.create({id: 1, name: 'kitty'}).exec(console.log);
```
...and then create a post:
```javascript
Post.create({id: 10, chitchat: 'kitty\'s talking so pay respect dude!', owner:1}).exec(console.log);
```

Very strangely:
```javascript
//=> 0
User.findOne(1).exec(function(err, r){console.log(r.posts.length)});

//=> 1
User.findOne(1).populate('posts').exec(function(err, r){console.log(r.posts.length)});
```
So unless one calls populate, the posts (or their IDs) aren't there.

Checking the mongo db, it seems collection user wasn't updated with the post.... the posts property doesn't exist there (not sure if this is the correct behaviour based on the via specified in the model).

### Update 1
Some more testing:
```javascript
//after running all the above code, doing this won't resolve the inconsistency
Post.update({id: 10}, {owner:1}).exec(console.log);

//but doing this instead will sync both collections and correct the inconsistency
User.update({id: 1}, {pets:[1]}).exec(console.log);
```
Seems like one would need to set associations from the N side rather than from the 1 side?!

**Comment by devinivy** [comment]
On most adapters I would say this is working as expected.  You only get associated records if you ask for them using `populate`.  That is, responding to this;
>Checking the mongo db, it seems collection user wasn't updated with the post.... the posts property doesn't exist there (not sure if this is the correct behaviour based on the via specified in the model).

Yes, that's typically correct.  There are some people working on embedded associations for the mongo adapter, so that could change.  But on most adapters (and I assume the same for mongo?) the `id`s only live on the 1 side.  It's the adapter's job when populating to grab all record on the 1 side and attach them to proper record on the N side.  So, I'd expect that the record on the N side (your user) doesn't know anything about which records should be attached to it– not until you use populate.

It is a feature of `Collection#update` that you can resync associated records, as you have done.  But I would not typically expect those associated ids to appear in the mongo db _on a user_ after update.  If that's occurring I think we need to ask the collaborators of sails-mongo why it's working that way.

To be clear, after doing this:

```javascript
//but doing this instead will sync both collections and correct the inconsistency
User.update({id: 1}, {pets:[1]}).exec(console.log);
```
are you finding an array of pet ids on your User?  Seems odd.

**Comment by anasyb** [comment]
Thanks @devinivy for the promptness :)

> On most adapters I would say this is working as expected. You only get associated records if you ask for them using populate. That is, responding to this;

Indeed it is expected that you don't get the **records** unless you call populate, that's the purpose of life for populate() after all ;) But you should be getting an array of unpopulated IDs should you not call populate.. in particular you should never get a deceiving **empty** array in place of the IDs array!

> are you finding an array of pet ids on your User? Seems odd.

Yes after running that line: 1. am finding an array of pet ids in user collection in the db, 2. it syncs pet db collection correctly (like if I remove/add 1 pet from the array ```User.update({id: 1}, {pets:[....]```), and 3. now the ```User.findOne..(err, record){record.pets``` returns an array of pets IDs rather than just an empty array.

This is definitely a fat inconsistency bug... in fact for me its also a serious data corruption bug that's putting my project behind. Updating/creating via Pet model isn't syncing User model, but update via User is syncing Pet.

Am on waterline 0.10.18

**Comment by devinivy** [comment]
I think this depends on the expected functionality of sails-mongo.  In my experience, most adapters would never return to you an array of ids of associated records–that seems wrong to me.  That said, I agree that it is possibly disingenuous to return an array at all in this case, unless populate has been called.  I think the confusion is related to https://github.com/balderdashy/sails-mongo/issues/254

**Comment by anasyb** [comment]
Yes confirmed by particlebanana this is a bug with mongo adapter... those arrays named after the associations are virtual attributes to facilitate add/remove and should never have PKs in them. I think, even after the mongo-related bug is solved, its very confusing and not so consistent: cardinality 1 relations don't have a virtual attribute.

Am closing this now until https://github.com/balderdashy/sails-mongo/issues/254 get resolved.
