### ISSUE TITLE
Include total amount of pages/records when using paginate

### ISSUE THREAD

**Issue by jonathanwiesel** [balderdashy/waterline#947]
I believe it would be really useful when using `paginate()` that you could have the total amount of pages (or at least record) available, so you can:

* Prepare your UI for the amount of pages available.

* You can select a specific page instead of keep incrementing your `page` parameter until you reach an uncertain end in some point.

**Comment by devinivy** [comment]
I'll let some people chime-in here.  I don't think this is a good direction for waterline, though, given that it would be easy to use `Collection#count` to achieve this.  This feature would require `paginate` to do additional queries, and some users may not want that.

**Comment by tjwebb** [comment]
> Prepare your UI for the amount of pages available.

You can always run a `count` query separately, right? Not all users may want or need a count; e.g. a total count is unnecessary when using infinite scrolling to page results.

**Comment by randallmeeker** [comment]
In order for it to be a non breaking change waterline would have to return a second value. Something like ```.exec(err, result, totalrecords)```

It do have plenty of pagination in sails that lack the total count and people just surf next / previous. But that is probably a result of me just being lazy and not wanting to write the extra query. If sails did it already then it would probably have been used. 

I am of two minds. A.) It is so easy to run the second query to get the count, it may not be worth the effort to open up waterline to achieve this. B.) It's fairly common feature in other frameworks and could easily be turned on with a switch on the ```find()``` so as to be backwards compatible and not run the extra query if not asked for.

**Comment by kevinburkeshyp** [comment]
From experience at a previous company, `SELECT COUNT(*)` gets extremely problematic when a) the counts get extremely large and b) you're doing a lot of writes. You also can't turn it off if you've documented it as part of your public API.

Depending on the table design, fetching a specific page of records gets extremely problematic as well as data sets get large. say you fetch page 7 (`SELECT ... LIMIT 400 OFFSET 350`)  and meanwhile 5 new records are written. Now you fetch page 8 (`SELECT ... LIMIT 450 OFFSET 400`, which means you have to fetch all 450 records into memory just to discard 400 of them). What does page 8 represent? You probably have five duplicate records in that list.

paging by following ID's (`GET /records?after=123`), with a serial key (`SELECT ... WHERE id > 123 LIMIT 50`), will a) avoid duplicates and b) be pretty easy to support with only an index on the serial column.

**Comment by randallmeeker** [comment]
@kevinburkeshyp You could turn it on and off if its triggered by the API. ```MODEL.find({returnTotalCount=true}).exec(function(err,result,count){/*...*/}``` The default could be false so that waterline works the same as previous versions, but allow for a second value to be returned with the count for those who with to turn it on. (however I defer to my statement above where it maybe more work that it's worth)

Your second point is valid (except I would not call it *extremely* problematic), but does not really change this issue as the same ```count()``` method would be used when seeking or pagination. However your solution is on point and is being considered here https://github.com/balderdashy/waterline/issues/918

**Comment by dmarcelino** [comment]
I think the best solution for this issue is #918.

Alternatively the user can do 2 separate queries as @tjwebb suggested as it's probably more transparent than having waterline doing it under the covers.

**Comment by dmarcelino** [comment]
@jonathanwiesel, I believe either @tjwebb's suggestion in https://github.com/balderdashy/waterline/issues/947#issuecomment-92085121 or #918 are the solution for your issue so I'm closing it for now. Please reopen if you feel otherwise.

**Comment by kevinburkeshyp** [comment]
More thoughtful analysis here, if you're curious - https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

**Comment by dmarcelino** [comment]
@kevinburkeshyp is that different from what is being purposed in #918: Feature Request: Seek/Keyset Pagination?

**Comment by randallmeeker** [comment]
We need to recognize that two different issues are being discussed here. #918 and *seeking* has little to do with THIS issue of returning page counts. It is an alternative methodology for pagination. In either case a Model.count() would have to be executed no matter which method you use. As @tjwebb pointed out a separate query can be used and should be used so that those that do not need the extra call do not get the performance hit. 

If your using blueprints you can modify your blueprints to return total counts as well. Here are templates
https://github.com/randallmeeker/SailsBluePrintActions/tree/master/pagination
