### ISSUE TITLE
Date fields on postgres auto-dec 1 day on sails lift with migrate: 'alter'.

### ISSUE THREAD

**Issue by Zax** [balderdashy/waterline#958]
Strange bug, 
i configure a model with 'date' field and i observed this field on database (postgres). After all restart (sails lift) the field is decreased by one day, on develelop env (migration set on 'alter').
If i switch env on production (migration set on 'save'), all right.

**Comment by dmarcelino** [comment]
@Zax, what is your timezone? I believe this is a sails-postgresql timezone issue, check balderdashy/sails-postgresql#153 please.

**Comment by Zax** [comment]
My timezone now is +2 (Rome). I do not understand why bug is present only on migration:'alter'.

**Comment by dmarcelino** [comment]
I don't think it's only on `migration:'alter'` because we were able to pick it up on sails-postgresql automated tests by changing the timezone. Anyway, it sounds like the same issue, so I'm closing this one. Please continue the discussion in balderdashy/sails-postgresql#153 so we have a single point of reference.
