### ISSUE TITLE
Nested update fails required validation

### ISSUE THREAD

**Issue by alin-roman-zitec** [balderdashy/waterline#964]
Hello, here we have two models:

User:

    attributes: {
        name: { type: 'string', required: true },
        posts: { collection: 'post', via: 'author' }
    }

Post:

    attributes: {
        title: { type: 'string', required: true },
        text: { type: 'string' },
        author: { model: 'user', required: true }
    }

We populate the user like this:

    User.create({ name: 'Test user', posts: [
        { title: 'Test post', text: 'some text' }
    ]).exec(console.log);

This creates a user with ID = 1 and a post with ID = 1 associated with the created user.

Now, if we update the user like so:

    User.update({ id: 1 }, { posts: [
        { id: 1, title: 'Test post - changed' }
    ] }).exec(console.log).catch(console.error);

The code throws a validation exception because it tries to set the author (which is required) to null in the process of updating, here: https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/nestedOperations/update.js#L440-L442

**Comment by dmarcelino** [comment]
Looks like a bug.

**Comment by devinivy** [comment]
The way nested updates works is as such,

1. When an id is specified on a nested record passed to `Collection#update`, update those nested records.
2. Remove all associations with the parent record, either by removing associations from a junction table (m:n) or by setting child record foreign keys to null (1:n).
3. For those nested records passed to `Collection#update` without specified without ids, create them.
4. Gather ids from all nested records, now created or updated, and associate those records with the parent record.

Step two is failing for you.  In your case, since nested updates reset associations entirely, doing updates like this is generally _bound_ to orphan post records, which isn't allowed.  If your records aren't allowed to be orphaned, it might be better to update those child records directly, so that their foreign keys are explicitly switched.  I hope it's clear: doing a nested update like this will leave you with exactly one post associated with your used.

That said, the nested update routine could sidestep this issue by issuing a query for all associated child records then performing a diff to minimize the number of associations that need to be destroyed.  That does add overhead to this already-expensive routine.

**Comment by dmarcelino** [comment]
Thanks @devinivy, so this isn't a bug *per se* but more of a limitation. Your suggestion on the last paragraph actually sounds quite good. On one side the diff would consume some computing but on the other there wouldn't be any unnecessary remove/add actions so that could balance the performance impact.

PS: @devinivy that's a great piece of information and should be in some sort of development wiki!

**Comment by alin-roman-zitec** [comment]
Yea, I get it.

This is the correct behavior because, when updating the user - post associations, any post that is no longer associated with the user is failing the validation - it cannot have a null author. In that case, one option is to delete the invalid post, but again, this is not an expected behavior and I don't recommend to implement it in waterline core.

My remaining solution is to override the update method of the blueprint controller to make the damn diff, delete the removed posts, update the existing ones and create the new posts.

Thank you for your quick responses.

**Comment by devinivy** [comment]
Sure thing!  The other possibility is to make two API calls to your blueprint controllers... one to update user info, and one to update post info.

**Comment by alin-roman-zitec** [comment]
That too, but I dislike multiple calls to API when I can make just one.

**Comment by dmarcelino** [comment]
For reference, there is an ongoing discussion on #975 regarding fixing this issue.
